### ISSUE TITLE
please correct your "NOTE"

### ISSUE THREAD

**Issue by ghost** [protomens/totui#2]
Please  include `You must have chrome browser pre-installed` in the opening sequence to the code. 

```
NOTE: 

We will open a browser and log you into your account to handle certain operations
```

So that it says this:
```
NOTE: 

You must have chrome browser pre-installed

We will open a browser and log you into your account to handle certain operations
```

**Comment by protomens** [comment]
added in https://github.com/protomens/totui/commit/a13cfea80f4ab870c1a2af56ba112def563fdecd
